### PR TITLE
Structural plasticity

### PR DESCRIPTION
**Pull request by pabogdan**
Added 2 examples of networks using structural plasticity.  

Once we add recordings to structural plasticity, 1 extra might be useful.

Depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/460

### CODE REVIEW

**Review by alan-stokes — CHANGES_REQUESTED** [review]
same issues as pynn8 examples, please fix accordingly

**Review by dkfellows — APPROVED** [review]
Looks OK to me

**Comment by pabogdan** [comment]
It is not currently possible, using PyNN7 interface, to extract the data that I need without the use private methods. As @rowleya pointed out, I could ask for a matrix with nans everywhere, except for the entries which have connections, however this has the side effect of not being able to correctly determine the number of connections (multpases are possible) between the same source-target pair. Leaving this as is, but changing the PyNN8+ example.

**Comment by alan-stokes** [comment]
but to be holy honest, pyunn 0.75 is on its way out. we already accepted that functionality wouldnt be backdated to it. Say structual is only pynn 0.8/0.9. only if its free or epically cheap do we backdate it, and breaking the api is not considered free or cheap. So given those assumptions that it isnt possible with pynn 0.75 interface, jsut remove the examples, or add a spinnaker_get_blah to a public part of spynnaker7, and we'll tkae that as an acceptance

**Comment by Christian-B** [comment]
As we are no longer updating pynn7 closing this pr but leaving the branch.

**Pull request closed without merging**
